# Site settings
title: The New Grad's Guide to Personal Finance
description: The New Grad's Guide to Personal Finance
base_url: "http://onkursen.com/personal-finance-guide"

# Build settings
markdown: kramdown

exclude: ["README.md"]
