# Site settings
title: The New Grad's Guide to Personal Finance
tag_text: The New Grad's Guide to Personal Finance
description: The New Grad's Guide to Personal Finance
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown

exclude: ["README.md"]
